networks:
  live-bootcamp-project:
    name: live-bootcamp-project

services:
  proxy:
    build:
      context: ./proxy
    image: legols122/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "3000:3000"
      - "8000:8000"
    depends_on:
      - auth-service
      - app-service
    networks:
      - live-bootcamp-project